---
releases:
  - name: alfajores-blockscout3
    chart: oci://us-west1-docker.pkg.dev/devopsre/clabs-public-oci/blockscout
    version: ~1
    createNamespace: false
    namespace: alfajores
    missingFileHandler: Error
    values:
      - ../values/values-alfajores-blockscout3.yaml
      - changeCause: {{ env "CHANGE_CAUSE" }}
{{ $imageTag := trim (env "BLOCKSCOUT_IMAGE_TAG") | default "" }}
{{ if ne $imageTag "" }}
      - blockscout:
          shared:
            image:
              tag: {{ $imageTag }}
{{ end }}
