{{- define "quai-blockscout.configmap" }}
apiVersion: v1
data:
  ACCOUNT_AUTH0_CALLBACK_URL: https://prime.{{- .Values.quaiBlockscout.chain -}}.quaiscan.io
  ACCOUNT_AUTH0_LOGOUT_URL: https://prime.{{- .Values.quaiBlockscout.chain -}}.quaiscan.io
  ACCOUNT_AUTH0_LOGOUT_RETURN_URL: https://prime.{{- .Values.quaiBlockscout.chain -}}.quaiscan.io
  BLOCKSCOUT_HOST: prime.{{- .Values.quaiBlockscout.chain -}}.quaiscan.io
  CHAIN_INDEX: <INDEX>
  ETHEREUM_JSONRPC_HTTP_URL: http://prime-go-quai-{{- include "quai-blockscout.envSuffix" $ -}}.{{- .Values.quaiBlockscout.env -}}.svc.cluster.local:<HTTP>
  ETHEREUM_JSONRPC_WS_URL: ws://prime-go-quai-{{- include "quai-blockscout.envSuffix" $ -}}.{{- .Values.quaiBlockscout.env -}}.svc.cluster.local:<WS>
  RUST_MULTICHAIN_SEARCH_URL: http://quai-blockscout-multichain-search-{{- include "quai-blockscout.envSuffix" $ -}}.{{- .Values.quaiBlockscout.env -}}.svc.cluster.local:8044
  SESSION_COOKIE_DOMAIN: .{{- .Values.quaiBlockscout.chain -}}.quaiscan.io
kind: ConfigMap
metadata:
  annotations:
  name: prime-{{- include "quai-blockscout.name" $ }}
  namespace: {{ .Values.quaiBlockscout.env }}
{{- end }}
