{{- define "quai-blockscout.bs" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: prime-{{ include "quai-blockscout.name" $ }}
  name: prime-{{ include "quai-blockscout.name" $ }}
  namespace: {{ .Values.quaiBlockscout.env }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: prime-{{ include "quai-blockscout.name" $ }}
  template:
    metadata:
      labels:
        app: prime-{{ include "quai-blockscout.name" $ }}
    spec:
      containers:
      - args:
        - sleep 9; mix ecto.create; mix ecto.migrate; mix phx.server
        command:
        - /bin/bash
        - -c
        env:
        - name: ACCOUNT_ENABLED
          value: "true"
        - name: BLOCKSCOUT_VERSION
          value: {{ .Values.quaiBlockscout.image.version }}
        - name: COIN
          value: QUAI
        - name: COIN_NAME
          value: QUAI
        - name: ECTO_USE_SSL
          value: "false"
        - name: ETHEREUM_JSONRPC_VARIANT
          value: geth
        - name: INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER
          value: "true"
        - name: LOGO
          value: /images/quai_logo.png
        - name: NETWORK
          value: QUAI
        - name: SUBNETWORK
          value: Prime
        - name: ACCOUNT_AUTH0_CALLBACK_URL 
          valueFrom:
            configMapKeyRef:
              key: ACCOUNT_AUTH0_CALLBACK_URL
              name: prime-{{ include "quai-blockscout.name" $ }}
        - name: ACCOUNT_AUTH0_LOGOUT_URL 
          valueFrom:
            configMapKeyRef:
              key: ACCOUNT_AUTH0_LOGOUT_URL
              name: prime-{{ include "quai-blockscout.name" $ }}
        - name: ACCOUNT_AUTH0_LOGOUT_RETURN_URL 
          valueFrom:
            configMapKeyRef:
              key: ACCOUNT_AUTH0_LOGOUT_RETURN_URL
              name: prime-{{ include "quai-blockscout.name" $ }}
        - name: BLOCKSCOUT_HOST
          valueFrom:
            configMapKeyRef:
              key: BLOCKSCOUT_HOST
              name: prime-{{ include "quai-blockscout.name" $ }}
        - name: CHAIN_INDEX
          valueFrom:
            configMapKeyRef:
              key: CHAIN_INDEX 
              name: prime-{{ include "quai-blockscout.name" $ }}
        - name: ETHEREUM_JSONRPC_WS_URL
          valueFrom:
            configMapKeyRef:
              key: ETHEREUM_JSONRPC_WS_URL
              name: prime-{{ include "quai-blockscout.name" $ }}
        - name: ETHEREUM_JSONRPC_HTTP_URL
          valueFrom:
            configMapKeyRef:
              key: ETHEREUM_JSONRPC_HTTP_URL
              name: prime-{{ include "quai-blockscout.name" $ }}
        - name: RUST_MULTICHAIN_SEARCH_URL 
          valueFrom:
            configMapKeyRef:
              key: RUST_MULTICHAIN_SEARCH_URL
              name: prime-{{ include "quai-blockscout.name" $ }}
        - name: SESSION_COOKIE_DOMAIN 
          valueFrom:
            configMapKeyRef:
              key: SESSION_COOKIE_DOMAIN
              name: prime-{{ include "quai-blockscout.name" $ }}
        - name: ACCOUNT_AUTH0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: ACCOUNT_AUTH0_CLIENT_ID 
              name: prime-{{ include "quai-blockscout.name" $ }}
        - name: ACCOUNT_AUTH0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: ACCOUNT_AUTH0_CLIENT_SECRET 
              name: prime-{{ include "quai-blockscout.name" $ }}
        - name: ACCOUNT_AUTH0_DOMAIN
          valueFrom:
            secretKeyRef:
              key: ACCOUNT_AUTH0_DOMAIN 
              name: prime-{{ include "quai-blockscout.name" $ }}
        - name: ACCOUNT_CLOAK_KEY
          valueFrom:
            secretKeyRef:
              key: ACCOUNT_CLOAK_KEY
              name: prime-{{ include "quai-blockscout.name" $ }}
        - name: ACCOUNT_DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: ACCOUNT_DATABASE_URL
              name: prime-{{ include "quai-blockscout.name" $ }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: prime-{{ include "quai-blockscout.name" $ }}
        - name: ACCOUNT_REDIS_URL
          valueFrom:
            secretKeyRef:
              key: ACCOUNT_REDIS_URL 
              name: prime-{{ include "quai-blockscout.name" $ }}
        image: {{ .Values.quaiBlockscout.image.name }}:{{ .Values.quaiBlockscout.image.version }}
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /blocks
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: blockscout
        ports:
        - containerPort: 4000
          name: http
          protocol: TCP
        resources: {}
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /blocks
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
{{- end }}
