version: '3.8'

services:
  stats-db:
    image: postgres:14
    restart: always
    container_name: 'stats-postgres'
    command: postgres -c 'max_connections=200'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7433:5432

  stats:
    platform: linux/x86_64
    depends_on:
      - stats-db
    image: ghcr.io/blockscout/stats:${STATS_DOCKER_TAG:-main}
    pull_policy: always
    restart: always
    container_name: 'stats'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-stats.env
    environment:
      - STATS__DB_URL=postgres://postgres:@stats-db:5432/stats
      - STATS__BLOCKSCOUT_DB_URL=postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
      - STATS__RUN_MIGRATIONS=true
    ports:
      - 8153:8050
