version: '3.9'

services:
  proxy:
    image: nginx
    container_name: '${SCHAIN_NAME}_proxy'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ${BLOCKSCOUT_PROXY_CONFIG_DIR:-../proxy}:/etc/nginx/templates
      - ${BLOCKSCOUT_PROXY_CERTS_PATH:-../certs}:/data/
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
      PROXY_PORT: ${PROXY_PORT:-80}
      HOST: ${HOST:-localhost}
    ports:
      - target: ${PROXY_BASE_PORT:-80}
        published: ${PROXY_PORT:-80}
      - target: 8080
        published: ${STATS_PORT:-8080}

