version: '3.9'

services:
  redis_db:
    extends:
      file: ./services/docker-compose-redis.yml
      service: redis_db

  db-init:
    extends:
      file: ./services/docker-compose-db.yml
      service: db-init

  db:
    extends:
      file: ./services/docker-compose-db.yml
      service: db

  backend:
    depends_on:
      - db
      - redis_db
    extends:
      file: ./services/docker-compose-backend.yml
      service: backend
    links:
      - db:database
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'ganache'
        ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8545/
        INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'true'
        INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
        CHAIN_ID: '1337'

  visualizer:
    extends:
      file: ./services/docker-compose-visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/docker-compose-sig-provider.yml
      service: sig-provider

  stats-db-init:
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats-db-init

  stats-db:
    depends_on:
      - backend
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats

  proxy:
    depends_on:
      - backend
      - stats
    extends:
      file: ./services/docker-compose-nginx.yml
      service: proxy