name: Build and Deploy to Dev
on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
jobs:
  buildDeployDev:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/build-deploy.yml
    secrets:
      DOCKER: ${{ secrets.DOCKER }}
      GH_PAT: ${{ secrets.GH_PAT }}
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
      GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    with:
      env: quai-dev
      awk: awk -F. '{print $1"."$2"."$3"."$4+1}'
      SESSION_COOKIE_DOMAIN: ${{ vars.SESSION_COOKIE_DOMAIN }}
