name: Publish Docker image for specific chain branches

on:
  push:
    branches:
      - production-filecoin
permissions:
  contents: read
  packages: write

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: build
    env:
      RELEASE_VERSION: 9.3.5
      DOCKER_CHAIN_NAME: filecoin
    steps:
      - uses: actions/checkout@v5
      - name: Setup repo
        uses: ./.github/actions/setup-repo
        id: setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          docker-remote-multi-platform: true
          docker-arm-host: ${{ secrets.ARM_RUNNER_HOSTNAME }}
          docker-arm-host-key: ${{ secrets.ARM_RUNNER_KEY }}

      - name: Build and push Docker image for Filecoin (indexer + API)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/blockscout/blockscout-${{ env.DOCKER_CHAIN_NAME }}-private:${{ env.RELEASE_VERSION }}-postrelease-${{ env.SHORT_SHA }}
          labels: ${{ steps.setup.outputs.docker-labels }}
          platforms: |
            linux/amd64
            linux/arm64/v8
          build-args: |
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}.+commit.${{ env.SHORT_SHA }}
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            CHAIN_TYPE=${{ env.DOCKER_CHAIN_NAME }}

      - name: Build and push Docker image for Filecoin (indexer)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/blockscout/blockscout-${{ env.DOCKER_CHAIN_NAME }}-private:${{ env.RELEASE_VERSION }}-postrelease-${{ env.SHORT_SHA }}-indexer
          labels: ${{ steps.setup.outputs.docker-labels }}
          platforms: |
            linux/amd64
            linux/arm64/v8
          build-args: |
            DISABLE_API=true
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}.+commit.${{ env.SHORT_SHA }}
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            CHAIN_TYPE=${{ env.DOCKER_CHAIN_NAME }}
