name: Release for Ethereum

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  OTP_VERSION: ${{ vars.OTP_VERSION }}
  ELIXIR_VERSION: ${{ vars.ELIXIR_VERSION }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: 6.9.0
    steps:
      - uses: actions/checkout@v4
      - name: Setup repo
        uses: ./.github/actions/setup-repo
        id: setup
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          docker-remote-multi-platform: true
          docker-arm-host: ${{ secrets.ARM_RUNNER_HOSTNAME }}
          docker-arm-host-key: ${{ secrets.ARM_RUNNER_KEY }}

      - name: Build and push Docker image for Ethereum (indexer + API)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: blockscout/blockscout-ethereum:latest, blockscout/blockscout-ethereum:${{ env.RELEASE_VERSION }}
          labels: ${{ steps.setup.outputs.docker-labels }}
          platforms: |
            linux/amd64
            linux/arm64/v8
          build-args: |
            DISABLE_WEBAPP=false
            API_V1_READ_METHODS_DISABLED=false
            API_V1_WRITE_METHODS_DISABLED=false
            CACHE_EXCHANGE_RATES_PERIOD=
            CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED=
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
            ADMIN_PANEL_ENABLED=false
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}-beta
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            CHAIN_TYPE=ethereum

      - name: Build and push Docker image for Ethereum (indexer)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: blockscout/blockscout-ethereum:${{ env.RELEASE_VERSION }}-indexer
          labels: ${{ steps.setup.outputs.docker-labels }}
          platforms: |
            linux/amd64
            linux/arm64/v8
          build-args: |
            DISABLE_API=true
            DISABLE_WEBAPP=true
            CACHE_EXCHANGE_RATES_PERIOD=
            CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED=
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
            ADMIN_PANEL_ENABLED=false
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}-beta
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            CHAIN_TYPE=ethereum

      - name: Build and push Docker image for Ethereum (API)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: blockscout/blockscout-ethereum:${{ env.RELEASE_VERSION }}-api
          labels: ${{ steps.setup.outputs.docker-labels }}
          platforms: |
            linux/amd64
            linux/arm64/v8
          build-args: |
            DISABLE_INDEXER=true
            DISABLE_WEBAPP=true
            CACHE_EXCHANGE_RATES_PERIOD=
            CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED=
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
            ADMIN_PANEL_ENABLED=false
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}-beta
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            CHAIN_TYPE=ethereum

      - name: Build and push Docker image for Ethereum (indexer + API)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: blockscout/blockscout-ethereum:${{ env.RELEASE_VERSION }}-shrink-internal-txs
          labels: ${{ steps.setup.outputs.docker-labels }}
          platforms: |
            linux/amd64
            linux/arm64/v8
          build-args: |
            DISABLE_WEBAPP=false
            API_V1_READ_METHODS_DISABLED=false
            API_V1_WRITE_METHODS_DISABLED=false
            CACHE_EXCHANGE_RATES_PERIOD=
            CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED=
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
            ADMIN_PANEL_ENABLED=false
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}-beta
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            CHAIN_TYPE=ethereum
            SHRINK_INTERNAL_TRANSACTIONS_ENABLED=true

      - name: Build and push Docker image for Ethereum (indexer)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: blockscout/blockscout-ethereum:${{ env.RELEASE_VERSION }}-shrink-internal-txs-indexer
          labels: ${{ steps.setup.outputs.docker-labels }}
          platforms: |
            linux/amd64
            linux/arm64/v8
          build-args: |
            DISABLE_API=true
            DISABLE_WEBAPP=true
            CACHE_EXCHANGE_RATES_PERIOD=
            CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED=
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
            ADMIN_PANEL_ENABLED=false
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}-beta
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            CHAIN_TYPE=ethereum
            SHRINK_INTERNAL_TRANSACTIONS_ENABLED=true

      - name: Build and push Docker image for Ethereum (API)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: blockscout/blockscout-ethereum:${{ env.RELEASE_VERSION }}-shrink-internal-txs-api
          labels: ${{ steps.setup.outputs.docker-labels }}
          platforms: |
            linux/amd64
            linux/arm64/v8
          build-args: |
            DISABLE_INDEXER=true
            DISABLE_WEBAPP=true
            CACHE_EXCHANGE_RATES_PERIOD=
            CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED=
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
            ADMIN_PANEL_ENABLED=false
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}-beta
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            CHAIN_TYPE=ethereum
            SHRINK_INTERNAL_TRANSACTIONS_ENABLED=true