name: Release for Zetachain

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

env:
  OTP_VERSION: '27.3.4.6'
  ELIXIR_VERSION: '1.19.4'

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: build
    env:
      RELEASE_VERSION: 9.3.5
    steps:
      - uses: actions/checkout@v5
      - name: Setup repo
        uses: ./.github/actions/setup-repo
        id: setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          docker-remote-multi-platform: true
          docker-arm-host: ${{ secrets.ARM_RUNNER_HOSTNAME }}
          docker-arm-host-key: ${{ secrets.ARM_RUNNER_KEY }}

      - name: Build and push Docker image for Zetachain (indexer + API)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/blockscout/blockscout-zetachain-private:latest, ghcr.io/blockscout/blockscout-zetachain-private:${{ env.RELEASE_VERSION }}
          labels: ${{ steps.setup.outputs.docker-labels }}
          platforms: |
            linux/amd64
            linux/arm64/v8
          build-args: |
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            CHAIN_TYPE=zetachain

      - name: Build and push Docker image for Zetachain (indexer)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/blockscout/blockscout-zetachain-private:${{ env.RELEASE_VERSION }}-indexer
          labels: ${{ steps.setup.outputs.docker-labels }}
          platforms: |
            linux/amd64
            linux/arm64/v8
          build-args: |
            DISABLE_API=true
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            CHAIN_TYPE=zetachain
